[package]
name = "novella"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11.1"
strum = "0.27.2"
tectonic = { git = "https://github.com/tectonic-typesetting/tectonic", branch = "master"}
